### ISSUE TITLE
Browsing files or folders fails complete after upgrade to 3.0.0 ( Nextcloud 24)

### ISSUE THREAD

**Issue by gmeks** [nextcloud/recognize#371]
**Describe the bug**
Browsing files or folders fails complete after upgrade to 3.0.0

`{"reqId":"bRYWcnFesqqFwn5RqB2I","level":4,"time":"2022-10-12T13:15:00+00:00","remoteAddr":"192.168.50.1","user":"firstname@gmail.com","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/firstname@gmail.com/2022%20-%20Lutsi%20bading","message":"Too few arguments to function OCA\\Recognize\\Dav\\RootCollection::__construct(), 0 passed in /var/www/html/apps/dav/lib/AppInfo/PluginManager.php on line 259 and exactly 8 expected","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0","version":"24.0.6.1","exception":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OCA\\Recognize\\Dav\\RootCollection::__construct(), 0 passed in /var/www/html/apps/dav/lib/AppInfo/PluginManager.php on line 259 and exactly 8 expected","Code":0,"Trace":[{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":259,"function":"__construct","class":"OCA\\Recognize\\Dav\\RootCollection","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":288,"function":"createClass","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"function":"OCA\\DAV\\AppInfo\\{closure}","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":293,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":158,"function":"loadSabreCollectionsFromInfoXml","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/PluginManager.php","line":106,"function":"populate","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":341,"function":"getAppPlugins","class":"OCA\\DAV\\AppInfo\\PluginManager","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\{closure}","class":"OCA\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":358,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/recognize/lib/Dav/RootCollection.php","Line":25,"CustomMessage":"--"},"id":"6346bdecdc4a8"}`

**To Reproduce**
1. Upgrade
2. Try to browse any folder with pictures

**Expected behavior**
Browsing pictures should show the pictures.

**Recognize (please complete the following information):**
 - JS-only mode: yes
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 24.0.6

**Additional context**
I will see if i can find more information when i get home from the office.
I also noticed that i lost all settings from during the upgrade.

**Comment by marcelklehr** [comment]
Thank you for the quick feedback. Nextcloud 24 was not supposed to be supported by v3 anymore, that's a mistake I'm going to rectify now.

**Comment by marcelklehr** [comment]
v3.0.0 is purged from the store, v3.0.1 now only supports 25 anymore
