### ISSUE TITLE
After upgrading to 3.6.0 NextCloud has been broken

### ISSUE THREAD

**Issue by z0ow** [nextcloud/recognize#715]
### Which version of recognize are you using?

3.6.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode, GPU mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Rocky Linux 8.7

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

24 GB

### What processor Architecture does your CPU have?

8

### Describe the Bug

after upgrading Recognize to 3.6.0 I could not access files on both the web interface and the client, NextCloud system overview alerted me there were some problems with the WebDAV configuration but accurately it is broken by Recognize.

This high-frequency fatal information is exported from Logging.

```
[recognize] Fatal: Error: Class "voku\helper\Bootup" not found at <<closure>>

0. /www/nextcloud/apps/recognize/vendor/composer/autoload_real.php line 55
   require()
1. /www/nextcloud/apps/recognize/vendor/composer/autoload_real.php line 38
   composerRequireed7f0a1d9dc886564ddbe2945c018806()
2. /www/nextcloud/apps/recognize/vendor/autoload.php line 25
   ComposerAutoloaderInited7f0a1d9dc886564ddbe2945c018806::getLoader()
3. /www/nextcloud/apps/recognize/lib/AppInfo/Application.php line 34
   include_once("/www/nextcloud/ ... p")
4. /www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 136
   OCA\Recognize\AppInfo\Application->register()
5. /www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 91
   OC\AppFramework\Bootstrap\Coordinator->registerApps()
6. /www/nextcloud/lib/base.php line 671
   OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
7. /www/nextcloud/lib/base.php line 1144
   OC::init()
8. /www/nextcloud/index.php line 34
   require_once("/www/nextcloud/lib/base.php")

POST /settings/apps/disable
from ###.###.###.### at 2023-03-07T01:40:17+00:00
```

and another fatal error is

```
[webdav] Error: ArgumentCountError: Too few arguments to function OCA\Recognize\Dav\RootCollection::__construct(), 0 passed in /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php on line 259 and exactly 8 expected at <<closure>>

 0. /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php line 259
    OCA\Recognize\Dav\RootCollection->__construct()
 1. /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php line 288
    OCA\DAV\AppInfo\PluginManager->createClass()
 2. <<closure>>
    OCA\DAV\AppInfo\PluginManager->OCA\DAV\AppInfo\{closure}("*** sensitive parameters replaced ***")
 3. /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php line 293
    array_map()
 4. /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php line 158
    OCA\DAV\AppInfo\PluginManager->loadSabreCollectionsFromInfoXml()
 5. /www/nextcloud/apps/dav/lib/AppInfo/PluginManager.php line 106
    OCA\DAV\AppInfo\PluginManager->populate()
 6. /www/nextcloud/apps/dav/lib/Server.php line 343
    OCA\DAV\AppInfo\PluginManager->getAppPlugins()
 7. /www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Server->OCA\DAV\{closure}("*** sensitive parameters replaced ***")
 8. /www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 456
    Sabre\DAV\Server->emit()
 9. /www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
10. /www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
11. /www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
12. /www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
13. /www/nextcloud/remote.php line 171
    require_once("/www/nextcloud/ ... p")

PUT /remote.php/dav/files/admin/.tabby/tabby-settings.json
from ###.###.###.### by admin at 2023-03-07T01:39:56+00:00
```

I have to disable the Recognize app and everything are seemed going right now.

### Expected Behavior

===

### To Reproduce

===

**Comment by marcelklehr** [comment]
Confirmed. I'll release a patch soon

**Comment by marcelklehr** [comment]
v3.6.1 is out now
